# Configuración para entorno de desarrollo

[general]
environment = "development"
debug = true
log_level = "DEBUG"

[server]
host = "0.0.0.0"
port = 8000
workers = 2
reload = true

[database]
type = "sqlite"
path = "storage/development.db"

[aws]
region = "us-east-1"
use_instance_profile = false  # Usar credenciales locales en desarrollo

[aws.s3]
enabled = true
bucket = "agent-isa-dev"
prefix = "development"

[aws.bedrock]
enabled = true
default_model = "anthropic.claude-3-sonnet-20240229-v1"

[aws.cloudwatch]
enabled = false  # Desactivado en desarrollo

[storage]
root_directory = "storage"
cache_directory = "cache"

[security]
enable_cors = true
allowed_origins = ["http://localhost:3000", "http://127.0.0.1:3000"]
jwt_secret = "development_secret_key_change_in_production"
jwt_expiry = 86400  # 24 horas

[logging]
file = "logs/development.log"
max_size = 10485760  # 10 MB
backup_count = 5
format = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

[monitoring]
enable_performance_metrics = true
sample_rate = 0.1  # 10% de las solicitudes
