# Configuración del módulo de Procesamiento de Contenido

[general]
enabled = true
cache_results = true
cache_expiry = 3600  # Segundos

[aws]
region = "us-east-1"

[extraction]
extract_tables = true
extract_links = true
extract_images = true
extract_metadata = true
max_content_length = 50000  # Caracteres
max_tables = 10
max_links = 100
max_images = 50

[analysis]
enable_sentiment_analysis = true
enable_entity_extraction = false  # Requiere bibliotecas adicionales
enable_summarization = false  # Requiere bibliotecas adicionales
enable_keyword_extraction = true

[tables]
normalize_headers = true
max_rows = 100
max_cols = 20

[text_processing]
remove_boilerplate = true
clean_whitespace = true
preserve_paragraphs = true
min_paragraph_length = 20  # Caracteres

[text_generation]
temperature = 0.7
max_tokens = 1000
default_style = "formal"
default_format = "markdown"
enable_revision = true

[media_processing]
enable_ocr = true
enable_image_analysis = true
max_image_size = 5242880  # 5MB
supported_formats = ["png", "jpeg", "jpg", "webp", "gif"]

[nova_models]
default_ocr_model = "amazon.nova-pro"  # Alternativa: "amazon.nova-lite"
default_analysis_model = "amazon.nova-pro"
default_image_generation_model = "amazon.nova-canvas"
default_video_model = "amazon.nova-reel"
