# Configuración del módulo de Búsqueda Web

[general]
enabled = true
cache_results = true
cache_expiry = 3600  # Segundos
default_language = "es"  # Idioma por defecto
default_country = "es"  # País por defecto

[search_engine]
default = "tavily"  # Cambiado a Tavily como motor predeterminado
results_per_page = 5
timeout = 10  # Segundos
max_retries = 3
retry_delay = 2  # Segundos

[search_engine.tavily]
api_key = ""  # Se cargará desde variables de entorno
search_depth = "basic"  # "basic" o "comprehensive"
include_domains = []
exclude_domains = []
include_answer = true
max_results = 5

[search_engine.google]
api_key = ""
cx = ""
use_api = false  # Si es false, usa web scraping
safe_search = "moderate"  # "off", "moderate", "strict"

[search_engine.bing]
api_key = ""
use_api = false
safe_search = "moderate"  # "off", "moderate", "strict"

[search_engine.duckduckgo]
safe_search = true

[browser]
headless = true
user_agent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"
timeout = 30  # Segundos
wait_for_selector = true
screenshot = false

[content_extraction]
extract_text = true
extract_images = false
extract_links = true
max_content_length = 10000  # Caracteres
